name = input("이름을 입력하세요: ")
id = input("학번을 입력하세요: ")
dep = input("학과를 입력하세요: ")
uni = input("학교를 입력하세요: ")
grade = input("학년을 입력하세요: ")
print("")
print("<출력>")
print(f"이름: {name}")
print(f"학번: {id}")
print(f"학번: {dep}")
print(f"학교: {uni}")
print(f"학년: {grade}")

